parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\State\ActivateAccount:
    bind:
      $decorated: '@api_platform.doctrine.orm.state.persist_processor'

  App\State\CreateRegistration:
    bind:
      $decorated: '@api_platform.doctrine.orm.state.persist_processor'

  App\State\OfferCreator:
    bind:
      $processor: '@api_platform.doctrine.orm.state.persist_processor'
      $security: '@security.helper'
      $entityManager: '@doctrine.orm.default_entity_manager'

  App\State\BidCreator:
    bind:
      $processor: '@api_platform.doctrine.orm.state.persist_processor'
      $security: '@security.helper'
      $entityManager: '@doctrine.orm.default_entity_manager'

  App\State\CloseOffer:
    bind:
      $entityManager: '@doctrine.orm.default_entity_manager'

  App\State\TestRegistrationEmail:
    bind:
      $entityManager: '@doctrine.orm.default_entity_manager'

  App\State\WhoAmI:
    bind:
      $security: '@security.helper'
      $entityManager: '@doctrine.orm.default_entity_manager'

  App\OpenApi\JwtDecorator:
    decorates: 'api_platform.openapi.factory'
    arguments: [ '@.inner' ]