parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\State\ActivateAccount:
    bind:
      $decorated: '@api_platform.doctrine.orm.state.persist_processor'

  App\State\CreateRegistration:
    bind:
      $decorated: '@api_platform.doctrine.orm.state.persist_processor'
      $mailer: '@mailer.mailer'

  App\State\ItemCreator:
    bind:
      $processor: '@api_platform.doctrine.orm.state.persist_processor'
      $security: '@security.helper'
      $entityManager: '@doctrine.orm.default_entity_manager'

  App\State\OfferCreator:
    bind:
      $processor: '@api_platform.doctrine.orm.state.persist_processor'
      $security: '@security.helper'
      $entityManager: '@doctrine.orm.default_entity_manager'

  App\State\OfferRetractor:
    bind:
      $processor: '@api_platform.doctrine.orm.state.persist_processor'
      $entityManager: '@doctrine.orm.default_entity_manager'

  App\State\BiddingCloser:
    bind:
      $entityManager: '@doctrine.orm.default_entity_manager'

  App\State\TestRegistrationEmail:
    bind:
      $entityManager: '@doctrine.orm.default_entity_manager'

  App\State\WhoAmI:
    bind:
      $security: '@security.helper'
      $entityManager: '@doctrine.orm.default_entity_manager'

  App\OpenApi\JwtDecorator:
    decorates: 'api_platform.openapi.factory'
    arguments: [ '@.inner' ]

  item.open_filter:
    parent: 'api_platform.doctrine.orm.boolean_filter'
    arguments: [ { item.open: ~ } ]
    tags: [ 'api_platform.filter' ]