App\Entity\Registration:
  operations:
    ApiPlatform\Metadata\Get: ~
    ApiPlatform\Metadata\Post:
      uriTemplate: "/register"
App\Entity\User:
  operations:
    ApiPlatform\Metadata\Get: ~
    ApiPlatform\Metadata\GetCollection: ~
    ApiPlatform\Metadata\Patch: ~