App\Entity\Registration:
  operations:
    ApiPlatform\Metadata\Get: ~
    ApiPlatform\Metadata\Post:
      uriTemplate: "/register"
App\Entity\User:
  operations:
    ApiPlatform\Metadata\Get: ~
    ApiPlatform\Metadata\GetCollection: ~
    ApiPlatform\Metadata\Patch: ~
App\Entity\Offer:
  operations:
    ApiPlatform\Metadata\Get: ~
    ApiPlatform\Metadata\GetCollection: ~
    ApiPlatform\Metadata\Post: ~
    ApiPlatform\Metadata\Patch: ~
    ApiPlatform\Metadata\Delete: ~
App\Entity\Bid:
  operations:
    ApiPlatform\Metadata\Get: ~
    ApiPlatform\Metadata\GetCollection: ~
    ApiPlatform\Metadata\Post: ~
    ApiPlatform\Metadata\Patch: ~
    ApiPlatform\Metadata\Delete: ~